spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients,/api/patients/**
          filters:
            - StripPrefix=1

server:
  port: 4004

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info