services:
  kafka:
    image: apache/kafka:latest # or your specific image
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - app-network

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: patient_management
      MYSQL_USER: root
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pmypass" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  analytics-service:
    build:
      context: ../analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    container_name: patient-analytics-service
    ports:
      - "4002:4002"
    depends_on:
      mariadb:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/patient_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypass
    networks:
      - app-network

  patient-service:
    build:
      context: ../patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      mariadb:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/patient_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypass
    networks:
      - app-network

  billing-service:
    build:
      context: ../billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
    depends_on:
      mariadb:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/patient_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypass
    networks:
      - app-network
#  docker compose up -d
#  docker compose build analytics-service
#  docker compose up -d analytics-service
#  docker compose logs -f analytics-service
networks:
  app-network: